name: Improve Code Quality

on:
  pull_request:
    branches:
      - production

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify Code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write **/*.{js,md}"
          only-changed: true
          file_pattern: "."