name: Improve Code Quality

on:
  pull_request:
    branches:
      - production

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Prettify Code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--write **/*.{js,md}"
          only-changed: true
          file_pattern: "."
      - name: Push changes
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/akama-aka/akami-statuspage.git
          git add -A
          git commit -m "Prettified code"
          git push origin ${{ github.head_ref }}
